# Generated by Django 4.0.4 on 2022-05-05 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_rename_price_room_room_price_bill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(max_length=15)),
                ('opening_hour', models.CharField(max_length=15)),
                ('closing_hour', models.CharField(max_length=15)),
                ('location', models.CharField(max_length=15)),
                ('phone_number', models.CharField(max_length=15)),
                ('footer_text', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(
            name='bill',
            options={'verbose_name_plural': 'Bill'},
        ),
    ]
